name: Docker CI for ONNX Predictor

on:
  push:
    branches: [ dev, prod ]
  pull_request:
    branches: [ prod ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies para tests
      run: |
        python -m pip install --upgrade pip
        pip install boto3 onnxruntime numpy

    - name: Run ONNX model tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        python test_onnx_pred.py

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ github.ref_name }}
        docker build -t onnx_model_pred:$IMAGE_TAG .

    - name: Run basic container test
      run: |
        IMAGE_TAG=${{ github.ref_name }}
        docker run --rm onnx_model_pred:$IMAGE_TAG echo "Contenedor $IMAGE_TAG construido correctamente"
